services:
  - type: web
    name: ticketing-client
    buildCommand: yarn run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html